### ISSUE TITLE
Cannot find module 'coffee-script'

### ISSUE THREAD

**Issue by vitortalaia** [achohq/acho#1]
Hi, nice work.

I installed this module via npm, but when trying to run an example code Node throws this error message in terminal.

I fixed it installing the coffescript module from npm then it worked properly. Is it something with package.json in the dependencies section?

**Comment by Kikobeats** [comment]
hey, I'm fixing and refactoring some things. Soon (today) I releases the first version of the library :-)

**Comment by vitortalaia** [comment]
So ok. I really like the simplicity of your library!

**Comment by Kikobeats** [comment]
@vitortalaia check now, If you detect something wrong or can be better please open another issue :-)

**Comment by vitortalaia** [comment]
:+1:
