### ISSUE TITLE
Global & Instance Log Levels

### ISSUE THREAD

**Issue by bennycode** [achohq/acho#20]
Does Acho supports setting a global log level and a log level per log instance?

**Comment by Kikobeats** [comment]
I don't understand you...

When you create an Acho instance, you can setup the log level.

The default level is `all`.

**Comment by Kikobeats** [comment]
I close that but you feel free to comment 😄

**Comment by bennycode** [comment]
Can I change the default log level for all newly created Acho instances?

**Comment by Kikobeats** [comment]
good point. Currently is not exposed, but I can do it.

what do you think that is better?
- Acho.defaults
- Acho.default

**Comment by Kikobeats** [comment]
Finally I'm going to expose it under `Acho.defaults` in the next release 👍

**Comment by bennycode** [comment]
Wow! That was quick. Thank you. 😃
